language: bash

addons:
  apt:
    update: true
    packages:
      - mtools

env:
  - RPI=rpi0
  - RPI=rpi1
  - RPI=rpi1b
  - RPI=rpi2
#  - RPI=rpi3
  - RPI=rpi3b
  - RPI=rpi4

script: 'bash ./compiler/get_compiler.sh && ./firmware/get_firmware_repo.sh && bash ./.build-all.sh'
