
/* This file is automatically generated by the tool create-random.py */
/* Command: ['./create-random-stars.py', '--count', '200'] */
/* x_multiplier: 16 */

#ifndef STARS_H
#define STARS_H

#define STARS_COUNT 200

typedef struct {
    int x;
    int y;
    int speed;
    } star_t;

extern star_t stars[STARS_COUNT];

#endif
